### ISSUE TITLE
Exception when trying to ignore a claim

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1024]
The following exception happens with our mainnet agents:

```
2022-09-13 23:23:28.550630 [debug    ] Claim changed state            [Claim] claim=<Claim id=31 state=ignored request_id=33>                                     
Traceback (most recent call last):                                                                                                                                
  File "/src/beamer/chain.py", line 45, in wrapper                                                                                                                
    return func(*args, **kwargs)                                                                                                                                  
  File "/src/beamer/chain.py", line 172, in _thread_func                                                                                                          
    process_claims(self._context)                                                                                                                                 
  File "/src/beamer/chain.py", line 277, in process_claims                                                                                                        
    claim.ignore()                                                                                                                                                
  File "/root/.cache/pypoetry/virtualenvs/beamer-VsnhxLU2-py3.9/lib/python3.9/site-packages/statemachine/statemachine.py", line 61, in __call__                   
    return self.func(*args, **kwargs)                                                                                                                             
  File "/root/.cache/pypoetry/virtualenvs/beamer-VsnhxLU2-py3.9/lib/python3.9/site-packages/statemachine/statemachine.py", line 85, in transition_callback        
    return self._run(machine, *args, **kwargs)                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/beamer-VsnhxLU2-py3.9/lib/python3.9/site-packages/statemachine/statemachine.py", line 191, in _run                      
    transition = self._verify_can_run(machine)                                                                                                                    
  File "/root/.cache/pypoetry/virtualenvs/beamer-VsnhxLU2-py3.9/lib/python3.9/site-packages/statemachine/statemachine.py", line 108, in _verify_can_run           
    raise TransitionNotAllowed(self, machine.current_state)                                                                                                       
statemachine.exceptions.TransitionNotAllowed: Can't ignore when in ChallengerWinning.                                                                             
```

**Comment by fredo** [comment]
The reason is that during sync, an agent could process all events from the source side first, bringing the claim into different states (i. e. challenger winning.) Once the corresponding fill is processed the claim suddenly becomes valid and the `ignore()` state change will be triggered in `process_claims()`
